name: dev_essentials
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/gairick-saha/dev_essentials.git

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.6
  collection: ^1.17.0
  intl: ^0.18.0
  dio: ^5.1.1
  progress_loading_button: ^2.0.2
  keyboard_dismisser: ^3.0.0
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0
  universal_io: ^2.2.0
  flutter_bloc: ^8.1.2
  mime: ^1.0.4
  flutter_svg: ^2.0.5
  path_provider: ^2.0.14
  path: ^1.8.2
  bot_toast: ^4.0.3
  device_preview: ^1.1.0
  sliver_tools: ^0.2.10
  reactive_forms: ^15.0.0
  reactive_pin_code_fields: ^1.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
